# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: 'edu-capstone:us-central1:psql_capstone'

runtime_config:
  python_version: 3
# [END runtime]
