# Generated by Django 3.1.4 on 2020-12-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_description', models.CharField(max_length=400)),
                ('cat_count', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1)),
                ('result', models.CharField(default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.CharField(max_length=500)),
                ('question_choice_1', models.CharField(max_length=200)),
                ('question_choice_2', models.CharField(max_length=200)),
                ('question_choice_3', models.CharField(max_length=200)),
                ('question_choice_4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=1)),
                ('category_id', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='n/a', max_length=3)),
                ('test_name', models.CharField(max_length=60)),
                ('graded', models.BooleanField(default=False)),
                ('student_username', models.CharField(max_length=20)),
                ('avg1', models.CharField(default='n/a', max_length=3)),
                ('avg2', models.CharField(default='n/a', max_length=3)),
                ('avg3', models.CharField(default='n/a', max_length=3)),
                ('avg4', models.CharField(default='n/a', max_length=3)),
                ('goal_score', models.CharField(default='n/a', max_length=3)),
                ('questions', models.ManyToManyField(through='app.Question_Attempt', to='app.Question_Data')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('average_total', models.CharField(max_length=3)),
                ('average_t1', models.CharField(max_length=3)),
                ('average_t2', models.CharField(max_length=3)),
                ('average_t3', models.CharField(max_length=3)),
                ('average_t4', models.CharField(max_length=3)),
                ('cat1_count', models.CharField(default=0, max_length=4)),
                ('cat2_count', models.CharField(default=0, max_length=4)),
                ('cat3_count', models.CharField(default=0, max_length=4)),
                ('cat4_count', models.CharField(default=0, max_length=4)),
                ('tests', models.ManyToManyField(through='app.Question_Attempt', to='app.Test_Data')),
            ],
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question_data'),
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test_data'),
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_data'),
        ),
        migrations.CreateModel(
            name='Class_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=60)),
                ('teacher_username', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(through='app.Class_Assignment', to='app.Student_Data')),
            ],
        ),
        migrations.AddField(
            model_name='class_assignment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class_section'),
        ),
        migrations.AddField(
            model_name='class_assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_data'),
        ),
    ]
